# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class testeve541nt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = testeve541nt()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAstesteve541nt(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # testeve541nt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def Start(builder): builder.StartObject(0)
def testeve541ntStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def End(builder): return builder.EndObject()
def testeve541ntEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)